/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MeshReact(props) {
    const { nodes, materials } = useGLTF('/react.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere.geometry}
                material={materials['Material.001']}
                position={[0, 0.011, -0.188]}
                scale={0.05}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus002.geometry}
                material={materials['Material.001']}
                position={[0, 0.011, -0.185]}
                rotation={[-Math.PI / 2, 1.043, -1.981]}
                scale={0.266}
            />
        </group>
    )
}

useGLTF.preload('/react.glb')

